// Code generated by MockGen. DO NOT EDIT.
// Source: app/repositories/interfaces/auth_repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=app/repositories/interfaces/auth_repository_interface.go -destination=app/mocks/mock_auth_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "golang_starter_kit_2025/app/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepositoryInterface is a mock of AuthRepositoryInterface interface.
type MockAuthRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryInterfaceMockRecorder is the mock recorder for MockAuthRepositoryInterface.
type MockAuthRepositoryInterfaceMockRecorder struct {
	mock *MockAuthRepositoryInterface
}

// NewMockAuthRepositoryInterface creates a new mock instance.
func NewMockAuthRepositoryInterface(ctrl *gomock.Controller) *MockAuthRepositoryInterface {
	mock := &MockAuthRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepositoryInterface) EXPECT() *MockAuthRepositoryInterfaceMockRecorder {
	return m.recorder
}

// FindUserByEmail mocks base method.
func (m *MockAuthRepositoryInterface) FindUserByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockAuthRepositoryInterfaceMockRecorder) FindUserByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).FindUserByEmail), email)
}

// FindUserByID mocks base method.
func (m *MockAuthRepositoryInterface) FindUserByID(id uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockAuthRepositoryInterfaceMockRecorder) FindUserByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).FindUserByID), id)
}

// UpdateUser mocks base method.
func (m *MockAuthRepositoryInterface) UpdateUser(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockAuthRepositoryInterfaceMockRecorder) UpdateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).UpdateUser), user)
}
