// Code generated by MockGen. DO NOT EDIT.
// Source: app/repositories/interfaces/role_repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=app/repositories/interfaces/role_repository_interface.go -destination=app/mocks/mock_role_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "golang_starter_kit_2025/app/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepositoryInterface is a mock of RoleRepositoryInterface interface.
type MockRoleRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryInterfaceMockRecorder is the mock recorder for MockRoleRepositoryInterface.
type MockRoleRepositoryInterfaceMockRecorder struct {
	mock *MockRoleRepositoryInterface
}

// NewMockRoleRepositoryInterface creates a new mock instance.
func NewMockRoleRepositoryInterface(ctrl *gomock.Controller) *MockRoleRepositoryInterface {
	mock := &MockRoleRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepositoryInterface) EXPECT() *MockRoleRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AssignPermissions mocks base method.
func (m *MockRoleRepositoryInterface) AssignPermissions(roleID uint, permissionIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignPermissions", roleID, permissionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignPermissions indicates an expected call of AssignPermissions.
func (mr *MockRoleRepositoryInterfaceMockRecorder) AssignPermissions(roleID, permissionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignPermissions", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).AssignPermissions), roleID, permissionIDs)
}

// Count mocks base method.
func (m *MockRoleRepositoryInterface) Count() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRoleRepositoryInterfaceMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).Count))
}

// Create mocks base method.
func (m *MockRoleRepositoryInterface) Create(role *models.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", role)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoleRepositoryInterfaceMockRecorder) Create(role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).Create), role)
}

// Delete mocks base method.
func (m *MockRoleRepositoryInterface) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).Delete), id)
}

// ExistsByName mocks base method.
func (m *MockRoleRepositoryInterface) ExistsByName(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByName", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByName indicates an expected call of ExistsByName.
func (mr *MockRoleRepositoryInterfaceMockRecorder) ExistsByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByName", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).ExistsByName), name)
}

// FindByID mocks base method.
func (m *MockRoleRepositoryInterface) FindByID(id uint) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRoleRepositoryInterfaceMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).FindByID), id)
}

// FindByName mocks base method.
func (m *MockRoleRepositoryInterface) FindByName(name string) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockRoleRepositoryInterfaceMockRecorder) FindByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).FindByName), name)
}

// GetAll mocks base method.
func (m *MockRoleRepositoryInterface) GetAll() ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRoleRepositoryInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).GetAll))
}

// GetPermissions mocks base method.
func (m *MockRoleRepositoryInterface) GetPermissions(roleID uint) ([]models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions", roleID)
	ret0, _ := ret[0].([]models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockRoleRepositoryInterfaceMockRecorder) GetPermissions(roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).GetPermissions), roleID)
}

// List mocks base method.
func (m *MockRoleRepositoryInterface) List(page, limit int) ([]models.Role, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, limit)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRoleRepositoryInterfaceMockRecorder) List(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).List), page, limit)
}

// ListWithPermissions mocks base method.
func (m *MockRoleRepositoryInterface) ListWithPermissions(page, limit int) ([]models.Role, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithPermissions", page, limit)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWithPermissions indicates an expected call of ListWithPermissions.
func (mr *MockRoleRepositoryInterfaceMockRecorder) ListWithPermissions(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithPermissions", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).ListWithPermissions), page, limit)
}

// Update mocks base method.
func (m *MockRoleRepositoryInterface) Update(role *models.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", role)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoleRepositoryInterfaceMockRecorder) Update(role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleRepositoryInterface)(nil).Update), role)
}
