// Code generated by MockGen. DO NOT EDIT.
// Source: app/repositories/interfaces/product_repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=app/repositories/interfaces/product_repository_interface.go -destination=app/mocks/mock_product_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "golang_starter_kit_2025/app/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductRepositoryInterface is a mock of ProductRepositoryInterface interface.
type MockProductRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockProductRepositoryInterfaceMockRecorder is the mock recorder for MockProductRepositoryInterface.
type MockProductRepositoryInterfaceMockRecorder struct {
	mock *MockProductRepositoryInterface
}

// NewMockProductRepositoryInterface creates a new mock instance.
func NewMockProductRepositoryInterface(ctrl *gomock.Controller) *MockProductRepositoryInterface {
	mock := &MockProductRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepositoryInterface) EXPECT() *MockProductRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockProductRepositoryInterface) Count() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockProductRepositoryInterfaceMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Count))
}

// CountByCategory mocks base method.
func (m *MockProductRepositoryInterface) CountByCategory(categoryID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCategory", categoryID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCategory indicates an expected call of CountByCategory.
func (mr *MockProductRepositoryInterfaceMockRecorder) CountByCategory(categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCategory", reflect.TypeOf((*MockProductRepositoryInterface)(nil).CountByCategory), categoryID)
}

// Create mocks base method.
func (m *MockProductRepositoryInterface) Create(product *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductRepositoryInterfaceMockRecorder) Create(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Create), product)
}

// Delete mocks base method.
func (m *MockProductRepositoryInterface) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Delete), id)
}

// FindByID mocks base method.
func (m *MockProductRepositoryInterface) FindByID(id uint) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProductRepositoryInterfaceMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProductRepositoryInterface)(nil).FindByID), id)
}

// FindByIDWithCategory mocks base method.
func (m *MockProductRepositoryInterface) FindByIDWithCategory(id uint) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDWithCategory", id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDWithCategory indicates an expected call of FindByIDWithCategory.
func (mr *MockProductRepositoryInterfaceMockRecorder) FindByIDWithCategory(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDWithCategory", reflect.TypeOf((*MockProductRepositoryInterface)(nil).FindByIDWithCategory), id)
}

// GetLowStockProducts mocks base method.
func (m *MockProductRepositoryInterface) GetLowStockProducts(threshold, page, limit int) ([]models.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLowStockProducts", threshold, page, limit)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLowStockProducts indicates an expected call of GetLowStockProducts.
func (mr *MockProductRepositoryInterfaceMockRecorder) GetLowStockProducts(threshold, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLowStockProducts", reflect.TypeOf((*MockProductRepositoryInterface)(nil).GetLowStockProducts), threshold, page, limit)
}

// List mocks base method.
func (m *MockProductRepositoryInterface) List(page, limit int) ([]models.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, limit)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockProductRepositoryInterfaceMockRecorder) List(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProductRepositoryInterface)(nil).List), page, limit)
}

// ListByCategory mocks base method.
func (m *MockProductRepositoryInterface) ListByCategory(categoryID uint, page, limit int) ([]models.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCategory", categoryID, page, limit)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByCategory indicates an expected call of ListByCategory.
func (mr *MockProductRepositoryInterfaceMockRecorder) ListByCategory(categoryID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCategory", reflect.TypeOf((*MockProductRepositoryInterface)(nil).ListByCategory), categoryID, page, limit)
}

// ListWithCategory mocks base method.
func (m *MockProductRepositoryInterface) ListWithCategory(page, limit int) ([]models.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithCategory", page, limit)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWithCategory indicates an expected call of ListWithCategory.
func (mr *MockProductRepositoryInterfaceMockRecorder) ListWithCategory(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithCategory", reflect.TypeOf((*MockProductRepositoryInterface)(nil).ListWithCategory), page, limit)
}

// Search mocks base method.
func (m *MockProductRepositoryInterface) Search(keyword string, page, limit int) ([]models.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", keyword, page, limit)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockProductRepositoryInterfaceMockRecorder) Search(keyword, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Search), keyword, page, limit)
}

// Update mocks base method.
func (m *MockProductRepositoryInterface) Update(product *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProductRepositoryInterfaceMockRecorder) Update(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Update), product)
}

// UpdateStock mocks base method.
func (m *MockProductRepositoryInterface) UpdateStock(productID uint, stock int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStock", productID, stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStock indicates an expected call of UpdateStock.
func (mr *MockProductRepositoryInterfaceMockRecorder) UpdateStock(productID, stock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStock", reflect.TypeOf((*MockProductRepositoryInterface)(nil).UpdateStock), productID, stock)
}
