// Code generated by MockGen. DO NOT EDIT.
// Source: app/repositories/interfaces/permission_repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=app/repositories/interfaces/permission_repository_interface.go -destination=app/mocks/mock_permission_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "golang_starter_kit_2025/app/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPermissionRepositoryInterface is a mock of PermissionRepositoryInterface interface.
type MockPermissionRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockPermissionRepositoryInterfaceMockRecorder is the mock recorder for MockPermissionRepositoryInterface.
type MockPermissionRepositoryInterfaceMockRecorder struct {
	mock *MockPermissionRepositoryInterface
}

// NewMockPermissionRepositoryInterface creates a new mock instance.
func NewMockPermissionRepositoryInterface(ctrl *gomock.Controller) *MockPermissionRepositoryInterface {
	mock := &MockPermissionRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPermissionRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepositoryInterface) EXPECT() *MockPermissionRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockPermissionRepositoryInterface) Count() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockPermissionRepositoryInterfaceMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockPermissionRepositoryInterface)(nil).Count))
}

// Create mocks base method.
func (m *MockPermissionRepositoryInterface) Create(permission *models.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPermissionRepositoryInterfaceMockRecorder) Create(permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionRepositoryInterface)(nil).Create), permission)
}

// Delete mocks base method.
func (m *MockPermissionRepositoryInterface) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPermissionRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPermissionRepositoryInterface)(nil).Delete), id)
}

// ExistsByName mocks base method.
func (m *MockPermissionRepositoryInterface) ExistsByName(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByName", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByName indicates an expected call of ExistsByName.
func (mr *MockPermissionRepositoryInterfaceMockRecorder) ExistsByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByName", reflect.TypeOf((*MockPermissionRepositoryInterface)(nil).ExistsByName), name)
}

// FindByID mocks base method.
func (m *MockPermissionRepositoryInterface) FindByID(id uint) (*models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPermissionRepositoryInterfaceMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPermissionRepositoryInterface)(nil).FindByID), id)
}

// FindByIDs mocks base method.
func (m *MockPermissionRepositoryInterface) FindByIDs(ids []uint) ([]models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ids)
	ret0, _ := ret[0].([]models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockPermissionRepositoryInterfaceMockRecorder) FindByIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockPermissionRepositoryInterface)(nil).FindByIDs), ids)
}

// FindByName mocks base method.
func (m *MockPermissionRepositoryInterface) FindByName(name string) (*models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(*models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockPermissionRepositoryInterfaceMockRecorder) FindByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockPermissionRepositoryInterface)(nil).FindByName), name)
}

// GetAll mocks base method.
func (m *MockPermissionRepositoryInterface) GetAll() ([]models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPermissionRepositoryInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPermissionRepositoryInterface)(nil).GetAll))
}

// List mocks base method.
func (m *MockPermissionRepositoryInterface) List(page, limit int) ([]models.Permission, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, limit)
	ret0, _ := ret[0].([]models.Permission)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPermissionRepositoryInterfaceMockRecorder) List(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPermissionRepositoryInterface)(nil).List), page, limit)
}

// Update mocks base method.
func (m *MockPermissionRepositoryInterface) Update(permission *models.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPermissionRepositoryInterfaceMockRecorder) Update(permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPermissionRepositoryInterface)(nil).Update), permission)
}
